### ISSUE TITLE
Styling does not load when locally linked to a local project

### ISSUE THREAD

**Issue by BenedictSu** [glints-dev/glints-aries#106]
For linking glints-aries locally to our employers project (following the instruction: https://github.com/glints-dev/glints-aries#how-to-test-local-changes-in-glints-aries-in-your-project), the styling became messed up even though it worked for the same version of glints-aries (remote) before linking.

**Comment by franciscrispin** [comment]
@BenedictSu do you have the `Loom` extension installed on your browser? If so, try uninstalling it. That worked for me. Figured it out from this issue haha https://github.com/styled-components/styled-components/issues/2254#issuecomment-557279833

**Comment by BenedictSu** [comment]
Closing issue as it is going stale
