### ISSUE TITLE
<Tooltip> component not working on mobile

### ISSUE THREAD

**Issue by franciscrispin** [glints-dev/glints-aries#108]
Currently we use `onTouchEnd` and `onTouchStart` event handlers as a quick fix to make the tooltip component usable on mobile. https://github.com/glints-dev/glints-aries/blob/v4/src/Display/Tooltip/Tooltip.tsx#L31

However this means the user has to click and hold on to the tooltip for it to appear which is porr UX. We need to implement something similar to the `hover` tooltip used by [material UI](https://material-ui.com/components/tooltips/#triggers)

Expected behaviour:
Desktop: Open on mouseover, Close on mouseleave
Mobile: Open on click, Close on click outside

Current behaviour: 
Desktop: Open on mouseover, Close on mouseleave :heavy_check_mark: 
Mobile: Open on touch, Closes on touch leave :x: 

Comments: 
- The `onMouseLeave` event is not supported by iOS https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html
- Another potential issue is on Safari because it handles click events differently https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event#Safari_Mobile

**Comment by franciscrispin** [comment]
Fixed in https://github.com/glints-dev/glints-aries/pull/117

**Comment by franciscrispin** [comment]
The tootip still cannot be closed on iOS for versions < 13.1.3

**Comment by franciscrispin** [comment]
@rosslo will help with this :smile:

**Comment by rosslo** [comment]
Fixed in https://github.com/glints-dev/glints-aries/pull/164
