### ISSUE TITLE
Add IconButton component

### ISSUE THREAD

**Issue by franciscrispin** [glints-dev/glints-aries#122]
We manually maintain different `IconButton` components in our existing codebases. There is a need to implement one on aries that will cover developers' common use-cases. Will have to consult our designers for this as well.

![image](https://user-images.githubusercontent.com/35050056/66289142-4cdee200-e90e-11e9-9004-a1a27e10f387.png)
![image](https://user-images.githubusercontent.com/35050056/66289164-62540c00-e90e-11e9-8a2d-173558789f21.png)

**Comment by iamfeek** [comment]
I feel that we should scope this to an `<Icon />` component instead that will simply print the icon out. 

So if we wanna use it in that button above, we can have something like:
```
<Button type="primary">
  GO TO PROFILE <Icon type="right-arrow" />
</Button>
```

With the `<Icon />` component, we can have it anywhere that can render out a component.
Like a `<h1>Hello <Icon type="wave" /></h1>`.

Instead of a more specific `IconButton` which I would imagine looking this:
```
<IconButton icon="right-arrow" position="right">
  GO TO PROFILE
</IconButton>
```

**Comment by franciscrispin** [comment]
Hmm yeah good idea. For the first example we probably still need to add a `position` prop so we can do this:

```
<Button type="primary">
  GO TO PROFILE <Icon name="right-arrow" position="right" />
</Button>
```

For the second screenshot, we probably can do something like:

```
<Button variant="ghost" icon="download" />
```

**Comment by franciscrispin** [comment]
Another way to do it is like material-ui, but I think the antd way reads better.

```
<Button
  variant="contained"
  color="primary"
  className={classes.button}
  endIcon={<Icon>send</Icon>}
>
  Send
</Button>

<Button
  variant="contained"
  color="default"
  className={classes.button}
  startIcon={<CloudUploadIcon />}
>
  Upload
</Button>
```

**Comment by iamfeek** [comment]
@franciscrispin Yeah, I agree that Antd reads better

**Comment by franciscrispin** [comment]
These are the icon buttons variants we need. The implementation is just my suggestion (based on antd Button components) but feel free to suggest alternative ways to do it.

![image](https://user-images.githubusercontent.com/35050056/66289142-4cdee200-e90e-11e9-9004-a1a27e10f387.png)

```
<Button type="primary">
  GO TO PROFILE <RightArrowIcon position="right" />
</Button>
```

![image](https://user-images.githubusercontent.com/35050056/66289164-62540c00-e90e-11e9-8a2d-173558789f21.png)

```
<Button variant="icon" icon="bookmark" shape="square" />
```

![image](https://user-images.githubusercontent.com/35050056/69302500-dcd5b280-0c54-11ea-99b2-37027dad4d1b.png)

```
<Button variant="icon" icon="close" shape="default" />
```
