### ISSUE TITLE
Remove GlintsContainer from library

### ISSUE THREAD

**Issue by franciscrispin** [glints-dev/glints-aries#123]
- GlintsContainer is too specific to our `dst` codebase and shouldn't be classified as a reusable component in `glints-aries`
- It should be moved to `dst` instead and removed from `glints-aries`

**Comment by westwood846** [comment]
@franciscrispin is this still relevant?

**Comment by westwood846** [comment]
Component has been updated, seems to me that it is relevant enough now. Apart from the name it is a fairly unspecific page container.
