### ISSUE TITLE
Optimize the bundle

### ISSUE THREAD

**Issue by rosslo** [glints-dev/glints-aries#141]
# Todo
- [x] Support ES Module to allow webpack to prune unused exports. https://github.com/glints-dev/glints-aries/pull/146
- [x] Refactor IconLibrary to avoid bundling unused Icons https://github.com/glints-dev/glints-aries/pull/151

**Comment by franciscrispin** [comment]
@rosslo Is this issue resolved now? :smile:

**Comment by rosslo** [comment]
@franciscrispin Haha yes, can close. 😄
