### ISSUE TITLE
react-dom should be declared as a peerDependency.

### ISSUE THREAD

**Issue by yjwong** [glints-dev/glints-aries#18]
Otherwise this results in two copies of react-dom being included into the bundle. 

Output from webpack-bundle-analyzer:

![image](https://user-images.githubusercontent.com/1174849/45265909-3bb27000-b485-11e8-8c54-96398a71688e.png)

**Comment by tagraha** [comment]
thx @yjwong , will be update the Dependencies

**Comment by tagraha** [comment]
I've created PR for the issue `https://github.com/glints-dev/glints-aries/pull/24` @yjwong @seahyc

**Comment by fredyyanto** [comment]
It's been fixed by @tagraha .. Thanks!
