### ISSUE TITLE
Tabs: Fix UI Mismatches

### ISSUE THREAD

**Issue by westwood846** [glints-dev/glints-aries#208]
GDS: https://app.abstract.com/share/e51821dd-be59-4c6f-99ad-6aeba45fa6e7?collectionLayerId=697d2f21-b538-4525-82bc-e9278ca156e0

**Comment by franciscrispin** [comment]
The PR related to this issue will also update the `tab` prop on `Tab.Pane` to accept an Element as well cc @ritikamotwani
