### ISSUE TITLE
Checkbox: control checkbox checked state resulted with a warning

### ISSUE THREAD

**Issue by no13000** [glints-dev/glints-aries#223]
React throws a warning when I attempted to control the `checked` value of a `Checkbox`.

```
<Checkbox
        id={...}
        checked={checked}
        value="..."
        onClick={...}
      />
```

![checkbox](https://user-images.githubusercontent.com/13257691/73816850-97bd2780-4824-11ea-98b0-658c94bf47b3.png)

**Comment by westwood846** [comment]
Can't reproduce
