### ISSUE TITLE
Select: input value should be controlled by the value prop only

### ISSUE THREAD

**Issue by rosslo** [glints-dev/glints-aries#224]
Related issue: https://glints.slack.com/archives/CS09D0LJX/p1580881897001900

**Comment by rosslo** [comment]
Reopen this issue because of https://glints.slack.com/archives/CS09D0LJX/p1594807261085300

**Comment by westwood846** [comment]
Closing this again. Workaround has been found and we're thinking of releasing a new Select to remedy all these Select problems.
