### ISSUE TITLE
Delay closing select

### ISSUE THREAD

**Issue by rosslo** [glints-dev/glints-aries#225]
When I select an option from the select, the selected option is not highlighted in grey with blue text. As a user, I do not know if I clicked on the option I intended to click. If it's possible, would be better to have the selected styles before the select closed.

Sample: https://ant.design/components/select 
antd delays closing select via slide-up animation, so that user can see the tapped option being highlighted.

**Comment by westwood846** [comment]
Gonna close this one since this is over a year old and we'll be releasing a new select component soon
