### ISSUE TITLE
Test Automatically on NPM Publish

### ISSUE THREAD

**Issue by westwood846** [glints-dev/glints-aries#242]
To make sure we don’t publish bad code, we should check if tests pass before publishing.

**Comment by rosslo** [comment]
Should also include **Formatting** and **Linting**.

**Comment by rosslo** [comment]
Automate bumping version and adding git tag

**Comment by rosslo** [comment]
PR: https://github.com/glints-dev/glints-aries/pull/246

**Comment by franciscrispin** [comment]
Oh could you also update the docs once the PR is merged :smile: https://github.com/glints-dev/glints-aries/wiki/Contributing#how-to-publish-a-new-version

cc @rosslo @westwood846
