### ISSUE TITLE
Button: Using `tag='a'` on PrimaryButton causes the text to change to the native `a` color

### ISSUE THREAD

**Issue by franciscrispin** [glints-dev/glints-aries#265]
Expected outcome: Color should still default to black for all states (active, hover, visited)

![image](https://user-images.githubusercontent.com/35050056/77385437-0fd6b100-6dc3-11ea-95dc-770234c68df5.png)

Code:
```
<Button variant="primary" theme="yellow" tag="a">
    <MailSolidIcon /> Sign up with email
</Button>
```

**Comment by rosslo** [comment]
Will fix this with https://github.com/glints-dev/glints-aries/issues/193
