### ISSUE TITLE
Button: new Link Button

### ISSUE THREAD

**Issue by rosslo** [glints-dev/glints-aries#304]
GDS: https://app.abstract.com/projects/da6f9bdf-2057-45bf-9dda-8dbf0d261eac/branches/master/commits/ea35c17cfaf8de11b7f8dcb588c859ba2d8d32eb/files/DDF7C217-39F9-45D7-8C53-8D8C88D5FC37/layers/083D78C7-FD27-47F5-B5BA-19041A61E7C1?mode=design

![image](https://user-images.githubusercontent.com/13249748/80338277-810bf700-888e-11ea-928e-b6fee709575f.png)

**Comment by westwood846** [comment]
We already have a link button. I'm guessing this is outdated.
