### ISSUE TITLE
Checkbox: Add renderAfterLabel prop

### ISSUE THREAD

**Issue by franciscrispin** [glints-dev/glints-aries#314]
- This is a follow up to this comment https://gitlab.glints.com/glints/glints-dst/-/merge_requests/1378/diffs#ac7f774ba874daf808ea0636491ca29fda0e03bb_0_20
- The use-case is to have an extra paragraph of text that is below the `label` but follows the same alignment of the `label` text.
- In the below example, I am hardcoding a `2em` margin  so that the extra text follows the same alignment but that is not ideal.
- I could put the extra text in the `label` prop but that is not ideal as that makes the extra text clickable. Disabling it with `pointer-events: none;` and `cursor: default` is also a bit hackish and not ideal.

![image](https://user-images.githubusercontent.com/35050056/80670750-4e563e80-8ada-11ea-8785-fdf42554a435.png)

![image](https://user-images.githubusercontent.com/35050056/80670778-6928b300-8ada-11ea-8fa6-e2ecb119be51.png)

**Comment by westwood846** [comment]
We'll wait for this to be added to GDS first.

**Comment by westwood846** [comment]
This won't be added to the design specs or implemented in Aries unless it gets used more than once.

https://glints.slack.com/archives/CS09D0LJX/p1594174423067500
