### ISSUE TITLE
Stroybook Pipeline Keep Failing

### ISSUE THREAD

**Issue by westwood846** [glints-dev/glints-aries#340]
Our https://buddy.works/ pipeline fails occasionally and this results in a 404 error for our Stroybook. This seems to have been happening more frequently recently.

![image](https://user-images.githubusercontent.com/3341028/82389001-8f07fe80-9a6d-11ea-8c6f-bf0df3d19677.png)

Current work-around is to re-run the pipeline manually.

**Comment by westwood846** [comment]
@tingtingdisco would you like to close this issue?

**Comment by tingtingdisco** [comment]
@westwood846 ok

**Comment by tingtingdisco** [comment]
there were 2 issues caused this problem:
1. buddy deleted some files during the upload to S3 step
2. sometimes memory is not enough for the build step

so we have updated buddy setting to always deploy from scratch. The memory issue is not happened frequently, so we will see if we need to migrate the deployment pipeline to github actions.
