### ISSUE TITLE
Select: Inconsistent behaviour of `onChange` function

### ISSUE THREAD

**Issue by franciscrispin** [glints-dev/glints-aries#343]
- The onChange function returns the `event` when typing into the input but returns the `value` of the `Select.Option` when clicking an item from the dropdown. This inconsistent behaviour results in code that looks like this when I want to handle the onChange differently:

```
onChange={(
  valueOrEvent: string | React.ChangeEvent<HTMLInputElement>
) => {
  if (typeof valueOrEvent === 'string') {
    handleValue(valueOrEvent); 
  } else {
    handleEvent(valueOrEvent)
  }
}}
```

Ideally the onChange should always return the `event`. Returning the `value` directly while seemingly convenient may not be the best practice as it leads to inconsistent behaviour.

**Comment by tingtingdisco** [comment]
added an `onInputChange` prop, but still need to check whether dependent projects rely on receiving the event object in the `onChange` callback.

cc @franciscrispin
