### ISSUE TITLE
Select: Unable to get property 'contains' of undefined or null reference

### ISSUE THREAD

**Issue by ritikamotwani** [glints-dev/glints-aries#360]
Reports of a Type error for select component 

TypeError · Unable to get property 'contains' of undefined or null reference
The trace contained 

```

if (!ReactDOM.findDOMNode(node.current).contains(element)) {
--
  | setIsFocus(false);
  | }
```

**Comment by westwood846** [comment]
Better treat this as confirmed, seems to have happened again. Attaching screenshots of Bugsnag error.

Happened on 	
https://employers.glints.sg/review/fdc1862f-fdc7-4e62-b984-f72f6dac13b5/candidates?status=NEW

![Screenshot 2020-06-15 at 16 24 55](https://user-images.githubusercontent.com/3341028/84634908-0c1b7c00-af25-11ea-9067-9a43f8daf841.png)
![Screenshot 2020-06-15 at 16 25 22](https://user-images.githubusercontent.com/3341028/84634911-0cb41280-af25-11ea-8075-32e45b4960ae.png)
![Screenshot 2020-06-15 at 16 25 30](https://user-images.githubusercontent.com/3341028/84634914-0d4ca900-af25-11ea-87a2-457ea2a5d198.png)
![Screenshot 2020-06-15 at 16 24 40](https://user-images.githubusercontent.com/3341028/84634895-0887f500-af25-11ea-8d09-cece0ede0238.png)

**Comment by westwood846** [comment]
Won't fix this for now. The error occurred in an outdated piece of code that will be removed when Glints-Aries is upgraded on DST.

**Comment by westwood846** [comment]
https://glints.slack.com/archives/CS09D0LJX/p1593647256041900
