### ISSUE TITLE
Gallery: Navigation through keys not working on clicking an image in the bottom row, when image modal is open.

### ISSUE THREAD

**Issue by ritikamotwani** [glints-dev/glints-aries#374]
<img width="1071" alt="Screenshot 2020-06-15 at 11 14 43 AM" src="https://user-images.githubusercontent.com/22127980/84625497-01e78680-af01-11ea-88bc-1afb481c7d17.png">

Steps:
1. Open the image modal.
2. Click on the imge from the bottom row.
3. Try to navigate by pressing the arrow keys.

**Comment by westwood846** [comment]
Fixed by https://github.com/glints-dev/glints-aries/pull/461
