### ISSUE TITLE
Investigate the use of rows property of TextArea

### ISSUE THREAD

**Issue by Kevintirta** [glints-dev/glints-aries#564]
Purpose: Investigate the use of rows property of textArea , if we do not use it we can possibility remove the properties and relevant methods, if we use it we can add more detailed and clear explanation

location: Textarea.tsx

related codes located at `handleChange` method

**Comment by ritikamotwani** [comment]
Not being used anywhere in the projects. 

Found a problem in the implementation as well:
![image](https://user-images.githubusercontent.com/22127980/108162322-e4fbf680-7112-11eb-84e0-5d78a68aa622.png)


After typing something
![image](https://user-images.githubusercontent.com/22127980/108162360-f5ac6c80-7112-11eb-8c1c-b8635d3a3877.png)

Should we remove it, as even in the design https://app.zeplin.io/project/5efe8c616e1cfb13f088fc06/screen/5fce0999a912e947572f4526 there's not a need of this?

**Comment by westwood846** [comment]
Prop has been removed
