### ISSUE TITLE
Select isFocus state is stalled after select text on text input

### ISSUE THREAD

**Issue by tingtingdisco** [glints-dev/glints-aries#582]
Select isFocus state is stalled after select text on text input, so the select dropdown is not shown.

https://www.loom.com/share/16e7fca028eb4576bc17c77328e42dd5

**Comment by westwood846** [comment]
Can't reproduce, checking if this is still an issue: https://glints.slack.com/archives/CS09D0LJX/p1614677379006600

**Comment by westwood846** [comment]
>when we select text inside the select input, if the mouse up event is triggered outside the select input, then the select dropdown cannot be shown unless we click outside the select and focus the select again.

Can reproduce with this. The mouseup has to be outside of the select.
