### ISSUE TITLE
Modal: full screen feature

### ISSUE THREAD

**Issue by rosslo** [glints-dev/glints-aries#607]
Since we have a few modals which are full screen in mobile, I think we can add a `fullScreen` prop to avoid keeping overwriting style in the project.

![image](https://user-images.githubusercontent.com/13249748/108166326-fce17380-712e-11eb-9e79-641a1397fde6.png)

![image](https://user-images.githubusercontent.com/13249748/108166348-066adb80-712f-11eb-9fc4-3aa6c0a6e50e.png)

**Comment by rosslo** [comment]
Zeplin: https://app.zeplin.io/project/5efe8c616e1cfb13f088fc06/screen/5f1543a7c5b99d9c703e1693

**Comment by westwood846** [comment]
Implemented by https://github.com/glints-dev/glints-aries/pull/630
