### ISSUE TITLE
Wrong color used for different states of <Breadcrumb> 

### ISSUE THREAD

**Issue by franciscrispin** [glints-dev/glints-aries#95]
[Trello Link](https://trello.com/c/3fgIY3DA/51-unexpected-behaviour-of-breadcrumb-reported-by-ven)

**Comment by ritikamotwani** [comment]
I would like to work on this.
Another Trello card related to this: https://trello.com/c/zYxi9e62/3275-unexpected-behaviour-of-breadcrumb-reported-by-ven
